name: autofix.ci

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: "auto"

      - name: Sync dependencies
        run: uv sync

      - name: Format code
        run: |
          set +e
          uv run ruff format .
          set -e

      - name: Lint code (fix)
        run: |
          set +e
          uv run ruff check --fix .
          set -e

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
